### PR TITLE
Add watch command / rework scanners

### PR DESCRIPTION
**Pull request by lespea**
1. Add a new "watch" command that watches the specified dirs for new files and tries parsing them
2. Add a path filter to trim down the files that we output (for watch)
3. Make sure all the scan logic is the same no matter what we do
4. Use feature flags to customize bin behavior

### CODE REVIEW

**Comment by luckman212** [comment]
This is a massive update! I won't be able to check it out until tomorrow but, big 👍

**Comment by luckman212** [comment]
Oh jeez. You're right 🤦

I had compiled a custom build, but an automation overwrote it some minutes later with 1.11.3. I've got that sorted now! But, still wrestling with the ulimit problem:

```
$ fse_dump -V
fse_dump 1.12.0-pre

$ sudo fse_dump watch
Password:
[2024-02-20T16:19:58Z INFO  fse_dump] Watching /System/Volumes/Data/.fseventsd/
Error:
   0: Too many open files (os error 24) about ["/System/Volumes/Data/.fseventsd/000000008bc53dc3"]

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

$ sudo ulimit -n 65535
$ sudo ulimit -u 65535

$ sudo fse_dump watch
[2024-02-20T16:20:10Z INFO  fse_dump] Watching /System/Volumes/Data/.fseventsd/
Error:
   0: Too many open files (os error 24) about ["/System/Volumes/Data/.fseventsd/000000008bc53dc3"]

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by lespea** [comment]
https://forums.developer.apple.com/forums/thread/735798

They posted to do this now apaprently:

```sh
launchctl limit maxfiles 256 unlimited
launchctl limit maxfiles 128000 524288
```

**Comment by luckman212** [comment]
I tried that but, no luck. Could very well be an OS bug as I'm running the 14.4 dev beta. Unfortunately I don't have any machines that _aren't_ running that beta. I'll keep researching.

**Comment by lespea** [comment]
Good luck I hope you can get it sorted.  That sounds very annoying.

**Comment by luckman212** [comment]
Based on [this][1] I tried

```
$ sudo launchctl limit maxfiles 128000 524288
$ ulimit -n 524288 10485760
```

Which worked, I was able to run `fse_dump`, but...
```
$ sudo fse_dump watch
[2024-02-20T22:13:11Z INFO  fse_dump] Watching /System/Volumes/Data/.fseventsd/

(...no output...)
```

[1]: https://apple.stackexchange.com/a/463534/100302

**Comment by lespea** [comment]
It can take a while since they files aren't generated until there are enough events in the memory buffer or whatever (not sure what the criteria is) so if there isn't much activity it could be a while.  But if you're sure that it's not working (you know new files are being created but there's no output) then I'll probably have to move to a polling method.  My initial watcher attempt locally wasn't working so I had to switch to kqueue but maybe that's broken too for some machines :(.

**Comment by lespea** [comment]
Okay I added a `--poll` option to watch -- can you try that out when you get a chance and see if that works?  It probably will be slower and chew through cpu unnecessarily but better than not working I guess.

**Comment by luckman212** [comment]
Just had a chance to try this. Compiled a fresh build.

But, it just runs and almost immediately exits (code 0):

```
$ sudo launchctl limit maxfiles 128000 524288
$ ulimit -n 524288 10485760

$ sudo fse_dump watch
[2024-02-24T03:25:49Z INFO  fse_dump] Watching /System/Volumes/Data/.fseventsd/
$ █

$ sudo fse_dump watch --poll
[2024-02-24T03:27:24Z INFO  fse_dump] Watching /System/Volumes/Data/.fseventsd/
$ █
```

**Comment by lespea** [comment]
That's what I get for not testing... the poll change caused the watcher to be dropped so it was immediately quitting.  Leaked the object(s) so it should work now.  Sorry bout that.

**Comment by luckman212** [comment]
I just tried the latest code. It stays running now, but still produces no output.

I tried with and without `--poll` and also tried running as root.

Parsing existing records appears to work fine; I was able to successfully run `fse_dump dump -c ~/test.csv`.

**Comment by lespea** [comment]
And just to confirm you're seeing new files show up in `/System/Volumes/Data/.fseventsd/` when watch is running?  Can you post an example of some of the new(est) filenames maybe the name schema changed and I'm filtering it?  There must be something we're missing; polling just re-reads the directory in a loop -- I don't see how it couldn't be seeing the new files?!?

**Comment by luckman212** [comment]
Hmm. You know I didn't even consider checking. Now that you mention it, apparently _NO_ there are not new fse files being generated. They only appear every 5-30 minutes when looking at the directory contents. Seems macOS is doing some sort of in-memory caching/aggregation of the events, only writing them out periodically to disk? I didn't realize this. So, it probably is working after all. 👍 

image

**Comment by lespea** [comment]
Okay that's what I assumed was happening.  I'm going to merge this then and work on a release Monday.  I tried finding some API to force flushing any cached events but I don't believe one exists.

**Pull request merged**
